# Docker Compose configuration for Frontend only
# Run with: make all

# TODO: Check what to do with volumes for the frontend and backend
# TODO: Confirm ports
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "5000:5000"
    env_file:
      - frontend/.env
    networks:
      - transcendence
    restart:
      on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
      - "5000:5000"
    networks:
      - transcendence
    restart:
      on-failure

  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    env_file:
      - postgresql/.env
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      - transcendence
    restart:
      on-failure

volumes:
  postgresql:
    name: postgresql
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: "${HOME}/data/database"

networks:
  transcendence:
    name: transcendence
    driver: bridge
