# Docker Compose configuration for Frontend only
# Run with: make all

# TODO: Check what to do with volumes for the frontend and backend
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      #vafernan - 11.05 - use real backend login via nginx proxy
      args:
        VITE_USE_MOCK: "false"
        #vafernan - 11.05 - use relative path for nginx proxy
        VITE_API_URL: "/api"
    container_name: frontend
    ports:
      - "443:443"
    env_file:
      - frontend/.env
    networks:
      - transcendence
    restart:
      on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    #vafernan - 11.05 - port 5555 for Prisma Studio only
    ports:
      - "5555:5555"
    volumes:
      - ${HOME}/data/uploads:/app/application/uploads
    env_file:
      - backend/.env
    networks:
      - transcendence
    restart:
      on-failure

  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    env_file:
      - postgres/.env
    volumes:
      - ${HOME}/data/database:/var/lib/postgresql/data
    networks:
      - transcendence
    restart:
      on-failure

networks:
  transcendence:
    name: transcendence
    driver: bridge
